spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev     # 开发环境
  application: 
    name: study-spring-cloud-config-dev
---
spring: 
  profiles: test    # 测试环境
  application: 
    name: study-spring-cloud-config-test
# 切记，一定要以utf-8保存